# The endpoint of the Azure AI Foundry project where your Agent will be created. It can be found in the project overview page. 
project_endpoint: https://yaoswal-ai-agent-resource.services.ai.azure.com/api/projects/yaoswal-ai-agent

# The name of model deployment to be used for your Agent. 
model_name: gpt-4o

# The endpoint for Azure AI Language service resource, Azure hub resource or Azure AI Foundry resource where your CLU and CQA projects are created. For example, https://my-resource.cognitiveservices.azure.com
language_resource_url: https://yaoswal-ai-agent-resource.services.ai.azure.com

# The connection name of the above resource when added in the Azure AI Foundry portal to your project
language_resource_connection_name: yaoswalcustomkey

# Go to the page of above connection in the Azure AI Foundry portal, then construct the connection ID by append "/connections/<language_resource_connection_name>" to the wsid parameter value in the page URL.
# For example, if the connection page URL contains "wsid=/subscriptions/<subscription_id>/resourceGroups/<resource_group_name>/providers/Microsoft.CognitiveServices/accounts/<account_name>/projects/<project_name>", 
# Then the connection ID is /subscriptions/<subscription_id>/resourceGroups/<resource_group_name>/providers/Microsoft.CognitiveServices/accounts/<account_name>/projects/<project_name>/connections/<language_resource_connection_name>
connection_id: /subscriptions/fecacd8c-07e7-4fad-a455-f65af8db70b3/resourceGroups/rg-yaoswal-7856/providers/Microsoft.CognitiveServices/accounts/yaoswal-ai-agent-resource/projects/yaoswal-ai-agent/connections/yaoswalcustomkey

# Project and deployment names for Conversational Language Understanding (CLU) and Custom Question Answering (CQA) that your Agent will use. 
cqa_project_name: yaoswal-ai-agent-cqa
cqa_deployment_name: test
clu_project_name: yaoswal-ai-agent-clu
clu_deployment_name: cluV1