#!/bin/bash
# env vars should have been set during provisioning:

set -e

cwd=$(pwd)
script_dir=$(dirname $(realpath "$0"))
cd ${script_dir}/..

echo "Generating .env file..."

cat << EOF > .env
export LOCATION="$LOCATION"
export RG_NAME="$RG_NAME"
export RG_SUFFIX="$RG_SUFFIX"

export USE_MI_AUTH="$USE_MI_AUTH"
export MI_ID="$MI_ID"
export MI_CLIENT_ID="$MI_CLIENT_ID"

export LANGUAGE_ENDPOINT="$LANGUAGE_ENDPOINT"
export CLU_PROJECT_NAME="$CLU_PROJECT_NAME"
export CLU_MODEL_NAME="$CLU_MODEL_NAME"
export CLU_DEPLOYMENT_NAME="$CLU_DEPLOYMENT_NAME"
export CLU_CONFIDENCE_THRESHOLD="$CLU_CONFIDENCE_THRESHOLD"
export CQA_PROJECT_NAME="$CQA_PROJECT_NAME"
export CQA_DEPLOYMENT_NAME="$CQA_DEPLOYMENT_NAME"
export CQA_CONFIDENCE_THRESHOLD="$CQA_CONFIDENCE_THRESHOLD"
export ORCHESTRATION_PROJECT_NAME="$ORCHESTRATION_PROJECT_NAME"
export ORCHESTRATION_MODEL_NAME="$ORCHESTRATION_MODEL_NAME"
export ORCHESTRATION_DEPLOYMENT_NAME="$ORCHESTRATION_DEPLOYMENT_NAME"
export ORCHESTRATION_CONFIDENCE_THRESHOLD="$ORCHESTRATION_CONFIDENCE_THRESHOLD"
export PII_ENABLED="$PII_ENABLED"
export PII_CATEGORIES="$PII_CATEGORIES"
export PII_CONFIDENCE_THRESHOLD="$PII_CONFIDENCE_THRESHOLD"

export AOAI_ENDPOINT="$AOAI_ENDPOINT"
export AOAI_DEPLOYMENT="$AOAI_DEPLOYMENT"
export EMBEDDING_DEPLOYMENT_NAME="$EMBEDDING_DEPLOYMENT_NAME"
export EMBEDDING_MODEL_NAME="$EMBEDDING_MODEL_NAME"
export EMBEDDING_MODEL_DIMENSIONS="$EMBEDDING_MODEL_DIMENSIONS"

export AGENTS_PROJECT_ENDPOINT="$AGENTS_PROJECT_ENDPOINT"
export MAX_AGENT_RETRY="$MAX_AGENT_RETRY"
export DELETE_OLD_AGENTS="$DELETE_OLD_AGENTS"

export SEARCH_ENDPOINT="$SEARCH_ENDPOINT"
export SEARCH_INDEX_NAME="$SEARCH_INDEX_NAME"

export STORAGE_ACCOUNT_NAME="$STORAGE_ACCOUNT_NAME"
export STORAGE_ACCOUNT_CONNECTION_STRING="$STORAGE_ACCOUNT_CONNECTION_STRING"
export BLOB_CONTAINER_NAME="$BLOB_CONTAINER_NAME"

export ACR_NAME="$ACR_NAME"

export ROUTER_TYPE="$ROUTER_TYPE"
EOF

cd ${cwd}

echo ".env file generated"
