#!/bin/bash

set -e

cwd=$(pwd)
script_dir=$(dirname $(realpath "$0"))
cd ${script_dir}/..

echo "Generating .env file..."

cat << EOF > .env
LOCATION=$LOCATION
RG_NAME=$RG_NAME
RG_SUFFIX=$RG_SUFFIX

USE_MI_AUTH=$USE_MI_AUTH
MI_ID=$MI_ID
MI_CLIENT_ID=$MI_CLIENT_ID

LANGUAGE_ENDPOINT=$LANGUAGE_ENDPOINT
CLU_PROJECT_NAME=$CLU_PROJECT_NAME
CLU_MODEL_NAME=$CLU_MODEL_NAME
CLU_DEPLOYMENT_NAME=$CLU_DEPLOYMENT_NAME
CLU_CONFIDENCE_THRESHOLD=$CLU_CONFIDENCE_THRESHOLD
CQA_PROJECT_NAME=$CQA_PROJECT_NAME
CQA_DEPLOYMENT_NAME=$CQA_DEPLOYMENT_NAME
CQA_CONFIDENCE_THRESHOLD=$CQA_CONFIDENCE_THRESHOLD
ORCHESTRATION_PROJECT_NAME=$ORCHESTRATION_PROJECT_NAME
ORCHESTRATION_MODEL_NAME=$ORCHESTRATION_MODEL_NAME
ORCHESTRATION_DEPLOYMENT_NAME=$ORCHESTRATION_DEPLOYMENT_NAME
ORCHESTRATION_CONFIDENCE_THRESHOLD=$ORCHESTRATION_CONFIDENCE_THRESHOLD
PII_ENABLED=$PII_ENABLED
PII_CATEGORIES=$PII_CATEGORIES
PII_CONFIDENCE_THRESHOLD=$PII_CONFIDENCE_THRESHOLD

AOAI_ENDPOINT=$AOAI_ENDPOINT
AOAI_DEPLOYMENT=$AOAI_DEPLOYMENT
EMBEDDING_DEPLOYMENT_NAME=$EMBEDDING_DEPLOYMENT_NAME
EMBEDDING_MODEL_NAME=$EMBEDDING_MODEL_NAME
EMBEDDING_MODEL_DIMENSIONS=$EMBEDDING_MODEL_DIMENSIONS

AGENTS_PROJECT_ENDPOINT=$AGENTS_PROJECT_ENDPOINT
MAX_AGENT_RETRY=$MAX_AGENT_RETRY
DELETE_OLD_AGENTS=$DELETE_OLD_AGENTS

SEARCH_ENDPOINT=$SEARCH_ENDPOINT
SEARCH_INDEX_NAME=$SEARCH_INDEX_NAME

STORAGE_ACCOUNT_NAME=$STORAGE_ACCOUNT_NAME
STORAGE_ACCOUNT_CONNECTION_STRING=$STORAGE_ACCOUNT_CONNECTION_STRING
BLOB_CONTAINER_NAME=$BLOB_CONTAINER_NAME

ACR_NAME=$ACR_NAME

ROUTER_TYPE=$ROUTER_TYPE
EOF

cd ${cwd}

echo ".env file generated"
