name: Azure Template Validation
on: 
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  pull-requests: write

jobs:
  template_validation_job:
    runs-on: ubuntu-latest
    name: template validation
    steps:
      - uses: actions/checkout@v4

      - uses: microsoft/template-validation-action@Latest
        id: validation
        env:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          AZURE_ENV_NAME: ${{ secrets.AZURE_ENV_NAME }}
          AZURE_LOCATION: ${{ secrets.AZURE_LOCATION }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          IS_GITHUB_WORKFLOW_RUN: ${{ vars.IS_GITHUB_WORKFLOW_RUN }}
          TRIAGE_AGENT_INJECT_EXAMPLES: ${{ vars.TRIAGE_AGENT_INJECT_EXAMPLES }}

          AZD_PARAM_ROUTER_TYPE: ${{ vars.AZD_PARAM_ROUTER_TYPE }}
          AZD_PARAM_GPT_MODEL_NAME: ${{ vars.AZD_PARAM_GPT_MODEL_NAME }}
          AZD_PARAM_GPT_MODEL_DEPLOYMENT_TYPE: ${{ vars.AZD_PARAM_GPT_MODEL_DEPLOYMENT_TYPE }}
          AZD_PARAM_GPT_MODEL_CAPACITY: ${{ vars.AZD_PARAM_GPT_MODEL_CAPACITY }}
          AZD_PARAM_EMBEDDING_MODEL_NAME: ${{ vars.AZD_PARAM_EMBEDDING_MODEL_NAME }}
          AZD_PARAM_EMBEDDING_MODEL_DEPLOYMENT_TYPE: ${{ vars.AZD_PARAM_EMBEDDING_MODEL_DEPLOYMENT_TYPE }}
          AZD_PARAM_EMBEDDING_MODEL_CAPACITY: ${{ vars.AZD_PARAM_EMBEDDING_MODEL_CAPACITY }}

      - name: print result
        run: cat ${{ steps.validation.outputs.resultFile }}
